package session

import (
	"context"
	"time"
)

// Service is a session storage service.
//
// It provides a set of methods for managing sessions and events.
type Service interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Delete(context.Context, *DeleteRequest) error
	// AppendEntry appends a durable session entry and applies its state delta.
	AppendEntry(context.Context, *AppendEntryRequest) error

	// Checkpoint methods
	GetCheckpoint(context.Context, *CheckpointRequest) (*Checkpoint, error)
	SaveCheckpoint(context.Context, *SaveCheckpointRequest) error
	ClearCheckpoint(context.Context, *CheckpointRequest) error

	// AgentState methods
	GetAgentState(context.Context, *AgentStateRequest) (*AgentState, error)
	SaveAgentState(context.Context, *SaveAgentStateRequest) error
	ClearAgentState(context.Context, *AgentStateRequest) error
}

// InMemoryService returns an in-memory implementation of the session service.
func InMemoryService() Service {
	return &inMemoryService{
		checkpoints: make(map[string]*Checkpoint),
		agentStates: make(map[string]map[string]*AgentState),
	}
}

// CreateRequest represents a request to create a session.
type CreateRequest struct {
	AppName string
	UserID  string
	// SessionID is the client-provided ID of the session to create.
	// Optional: if not set, it will be autogenerated.
	SessionID string
}

// CreateResponse represents a response for newly created session.
type CreateResponse struct {
	Session Session
}

// GetRequest represents a request to get a session.
type GetRequest struct {
	AppName   string
	UserID    string
	SessionID string

	// NumRecentEvents returns at most NumRecentEvents most recent events.
	// Optional: if zero, the filter is not applied.
	NumRecentEvents int
	// After returns events with timestamp >= the given time.
	// Optional: if zero, the filter is not applied.
	After time.Time
}

// GetResponse represents a response from [Service.Get].
type GetResponse struct {
	Session Session
}

// ListRequest represents a request to list sessions.
type ListRequest struct {
	AppName string
	UserID  string
}

// ListResponse represents a response from [Service.List].
type ListResponse struct {
	Sessions []Session
}

// DeleteRequest represents a request to delete a session.
type DeleteRequest struct {
	AppName   string
	UserID    string
	SessionID string
}

// AppendEntryRequest represents a request to append an entry to a session.
type AppendEntryRequest struct {
	AppName   string
	UserID    string
	SessionID string
	Entry     DurableEntry
}
